name: CI
on: [ push, pull_request ]

env:
  RUSTFLAGS: >-
    -Dwarnings
    -Clink-arg=-fuse-ld=mold
  RUST_BACKTRACE: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6
      - name: "Replace the pinned channel with 'stable'"
        run: sed -i 's/^channel = \".*\"/channel = \"stable\"/' rust-toolchain.toml #
      - name: Set home dirs
        run: |
          echo "MISE_DATA_DIR=$RUNNER_TEMP/mise" >> "$GITHUB_ENV"
          echo "RUSTUP_HOME=$RUNNER_TEMP/mise/rustup" >> "$GITHUB_ENV" # RUSTUP_HOME must live under MISE_DATA_DIR, so that mise caches it automatically (it doesn't cache ~/.rustup)
          echo "CARGO_HOME=$RUNNER_TEMP/mise/cargo" >> "$GITHUB_ENV" # CARGO_HOME must live under MISE_DATA_DIR, so that mise caches it automatically (it doesn't cache ~/.cargo)
      - uses: rui314/setup-mold@v1 # mold is a workaround for regression in Rust 1.93 beta
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false # mise already caches CARGO_HOME
      - run: lefthook run --force pre-commit
      - run: cargo hack test --feature-powerset
      - uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: true
          failOnErrors: true
